name: AxGraves
version: '${project.version}'
main: com.artillexstudios.axgraves.AxGraves
api-version: '1.21'
folia-supported: true

commands:
  axgraves:
    description: Main command for AxGraves
    usage: /axgraves
    aliases: [axgrave, graves, grave]
    permission: axgraves.help

permissions:
  axgraves.help:
    default: true
  axgraves.reload:
    default: op
  axgraves.list:
    default: true
  axgraves.list.other:
    default: op
  axgraves.tp:
    default: op
  axgraves.tp.bypass:
    default: op
  axgraves.allowgraves:
    default: true
  axgraves.limit.1:
    default: false
